[project]
name = "r2ai"
version = "0.2.0"
description = "Playing with radare 2 AI"
authors = ["Roman Valls Guimera <brainstorm@nopcode.org>"]
channels = ["pytorch-nightly", "conda-forge"]
platforms = ["osx-arm64"]

[tasks]
install_r2ai = "ln -sf $HOME/.local/share/radare2/r2pm/git/r2ai/main.py $HOME/.local/share/radare2/plugins/r2ai.py && ln -sf $HOME/.local/share/radare2/r2pm/git/r2ai/main.py  $HOME/.local/share/radare2/prefix/bin/r2ai && echo 'Radare2 AI installed'"

[pypi-dependencies]
tokentrim = "*"

[dependencies]
llama-cpp-python = "*"
torchaudio = "*"
pytorch = "*"
torchvision = "*"
appdirs = "*"
huggingface_hub = "*"
inquirer = "*"
rich = "*"
