[project]
name = "r2ai"
version = "0.2.0"
description = "Playing with radare 2 AI"
authors = ["Roman Valls Guimera <brainstorm@nopcode.org>"]
channels = ["pytorch-nightly", "conda-forge"]
platforms = ["osx-arm64"]

[tasks]
install_r2ai = "ln -sf $HOME/.local/share/radare2/r2pm/git/r2ai/main.py $HOME/.local/share/radare2/plugins/r2ai.py && ln -sf $HOME/.local/share/radare2/r2pm/git/r2ai/main.py  $HOME/.local/share/radare2/prefix/bin/r2ai && echo 'Radare2 AI installed'"

[pypi-dependencies]
tokentrim = "~=0.1.13"
llama-cpp-python = "~=0.2.19"

[dependencies]
torchaudio = "*"
pytorch = "*"
torchvision = "*"
appdirs = "1.4.4.*"
huggingface_hub = "0.18.0.*"
inquirer = "3.1.3.*"
rich = "13.6.0.*"
python = "3.11.6.*"
