[project]
name = "r2ai"
version = "0.1.0"
description = "Playing with radare 2 AI"
authors = ["Roman Valls Guimera <brainstorm@nopcode.org>"]
channels = ["pytorch-nightly", "conda-forge"]
platforms = ["osx-arm64"]

[tasks]
# This should not be needed on a newer pixi version
# PyPi is not yet integrated into Pixi
pypi = "pip install tokentrim llama-cpp-python"
# R2AI integration
r2ai = "ln -sf $HOME/.local/share/radare2/r2pm/git/r2ai/main.py $HOME/.local/share/radare2/plugins/r2ai.py && ln -sf $HOME/.local/share/radare2/r2pm/git/r2ai/main.py  $HOME/.local/share/radare2/prefix/bin/r2ai && echo 'Radare2 AI installed'"

[dependencies]
pip = "23.3.1.*"
torchaudio = "2.2.0.dev20231104.*"
pytorch = "2.2.0.dev20231104.*"
torchvision = "0.17.0.dev20231104.*"
appdirs = "1.4.4.*"
huggingface_hub = "0.18.0.*"
inquirer = "3.1.3.*"
rich = "13.6.0.*"
